### creates a new patient entity
Post http://localhost:4000/patients
Content-Type: application/json
{
"name": "Ehsan Abid22",
"email": "ehsan22@gmail.com",
"address": "Brigittaplatz 14",
"dateOfBirth": "2000-04-22",
"registeredDate":"2026-03-30"
}

###